sudo: false
language: java
jdk:
  - oraclejdk8
script:
  - mvn package
after_success:
    - 'if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then
        if [ ${TRAVIS_BRANCH} = "master" ]; then
          pip install --user awscli;
          export PATH=$PATH:$HOME/.local/bin;
          echo "Uploading artifact to s3";
          aws s3 cp target/PdfWatermarkerLambda.jar s3://$BUCKET/$FUNCTION_NAME;
          echo "Uploaded!";
        else
          echo "Skipping deploy because branch is not master";
        fi
      else
        echo "Skipping deploy because this is a pull request";
      fi'